# Generated by Django 4.0.4 on 2023-11-29 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default='0.00', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price in KSHS'),
        ),
    ]
